version: 0.0
os: linux
files:
  - source: /
    destination: /vhosts/dev.battle4kc.com/httpdocs
hooks:
  BeforeInstall:
  AfterInstall:
  - location: /vhosts/dev.battle4kc.com/perms.sh 
      timeout: 2
      runas: root
  ApplicationStart:
  ApplicationStop:
